### ISSUE TITLE
Spectator mode causes netplay disconnection

### ISSUE THREAD

**Issue by furiadeoso** [libretro/netplay-mitm-server#4]
Pressing "i" netplay spectator mode hotkey is causing netplay disconnection of all peers, including host.

**Comment by bparker06** [comment]
@GregorR Any idea on this one? Only seems to happen with MITM.

**Comment by furiadeoso** [comment]
By the way. There are another relay server issue not reported yet than could be related. Passsword (both server and spectator) are not working at all. 
I suppose that is because nobody is a real host.

**Comment by bparker06** [comment]
It can be added, but currently password support has not been implemented in MITM yet.

**Comment by Chaos81** [comment]
I can confirm this. When pressing "i" to enter spectating mode, netplay will disconnect.
